sudo: required

language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

before_install:
  - sudo apt-get install -qq pkg-config openssl libsodium-dev libopus-dev ffmpeg youtube-dl
  - youtube-dl -U