sudo: required

language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

before_install:
  # Install deps
  - sudo apt-get install -qq wget curl ffmpeg build-essential openssl

  # Install youtube-dl
  - sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
  - sudo chmod a+rx /usr/local/bin/youtube-dl

  # Install libsodium
  - wget https://download.libsodium.org/libsodium/releases/LATEST.tar.gz
  - tar xvfz LATEST.tar.gz
  - cd libsodium-*
  - ./configure
  - make
  - make install
  - cd ..

  # Install libopus
  - wget http://downloads.xiph.org/releases/opus/opus-1.1.3.tar.gz
  - tar xvfz opus-1.1.3.tar.gz
  - cd opus-1.1.3
  - ./configure
  - make
  - make install
  - cd ..
