language: go
go:
  - master
  - 1.8.x
  - 1.9.x
  - 1.10.x
install:
    - go get -u github.com/golang/dep/cmd/dep
    - dep ensure
    - go get -u github.com/jteeuwen/go-bindata/...
    - patch vendor/github.com/bwmarrin/discordgo/restapi.go patches/adds_robyul_discord_rest_api_logging.patch -R
    # update npm
    - npm install npm -g
    - npm install -g snyk
    - snyk test
    #- go get -v github.com/golang/lint/golint
    #- go get github.com/mitchellh/gox
script:
    - bash format_go.sh
    - go-bindata -nomemcopy -nocompress -pkg helpers -o helpers/assets.go _assets/
    - go test -v -race $(go list ./... | grep -v /vendor/)
    #- go vet -x ./...
    #- golint ./...
    #- gox -output="robyul2-{{.OS}}-{{.Arch}}" -osarch="windows/amd64"
after_success:
    - snyk monitor
deploy:
  provider: releases
  api_key:
    secure: BZnS+tH7kCy2Jpzl5ctIIlQqurIlLvJVw5Pn2tkjEnQlnEQZUW7dEI/eejz1Tw1NNjuxdfJRzgkTNI7sRM6VjtuoTzq772TuxncTv4Oy/t/S3zaBthMMl/8Ug+VW2Py/A6LO8YDVpEaIIenyUTsmPG99HJd7jjW+qCh3npfjvWvf4Qe3FL0cNOH6l9ptA77Fcu1j7yXOUqCpxVtLL8sRe9qTsciUGT8eSAaHLBKbUxcw4TMn4P7G1/6b4tfkm1aQZX5cJROccdYt6FY5z1hNUUUN3e1bn1Hj/iY2zUZm1F4LHC5AcfZFUu/fAGhoLbB1B/hEZ4zrE7RLKaCR1vWCbr54/Xn+uWdDWPL6dbJ3EzCIuDtGDoHAJBfRos9HsCdfizB5A/yg0OS3RscK7Umh+gEznJyQCvAIbndAaryxKeOxVPd6tIdoW0fi0yaWmq9UHKVUt7lLd8rxlGWhGh6/GPLCME7+EAR84RyvP7e6VUHxUSnB3bly3oeJZd/QZpHmrIPqE6K9iobDJyERjNd+Bvuay8bw65NcqR9ZtAYlK7tUYxyEhw23fyybrwTB7ONUu/DDUSLQrtP7YvhtGnxMS+cU4O5GZrkuIP7urUS5KAnYbzb5I3F1Bk8PDLNFEdsGUOKq9U5ywRypmVfSxldGQHvEl4x1CO3E3zJEhkDOIaI=
  file: robyul2-amd64.exe
  skip_cleanup: true
  on:
    repo: Seklfreak/Robyul2
    tags: true
    go: tip
notifications:
  webhooks:
    urls:
      - https://slmn.de/robyul-cord-travis-webhook/travis-ci.php
    on_success: always
    on_failure: always
    on_start: never
    on_cancel: always
    on_error: always
