sudo: true

language: go

go: 1.7.x

before_install:
    - sudo add-apt-repository ppa:masterminds/glide -y
    - sudo apt-get update
    - sudo apt-get install glide -y

install:
    - glide install

script:
    - GOOS=linux GOARCH=amd64 GOTARGET=karen.x64.o ./build.sh
    - GOOS=windows GOARCH=amd64 GOTARGET=karen.x64.exe ./build.sh

deploy:
  provider: releases
  api_key:
    secure: ApDqC0W4LD71zxUF6B739dE4z9Brrzg/UsNT7qBOS9qn7v/AZUyYJRnP625OmUJ8iyH/7pC7rCieVkufqOzE/jSGfw0TNWZCgENVtTdfd6A5pyE3KOh2mZ0nrKeJc2j9dKmOdc3cUBPhfQIE7lAgdFbv2fAPNTcB9GoqSNHYnenJzBFRvYvmiEMZ5FD3YGVsA7KM2hnfZ5YbAHuztWEfMR3DGp6t2Q4m3q4TnqqyVEomB3tNEfwjEy/W/Jo5d/wLdzbXjyLb/0DTv5KSEtFrQYH4b2K6GWsHEfQFEWbg1z5p8rSOw3UluesbdTkyukg/VHyjjladjoEpgcmhlxIgfj4IMM+K6lUFSzsInxM0300UGqdPdm7+4fJkIG71YK1m8buNElDmsYq7nB7xsZR5wdQ0dORtK+9WAMsUnK4Hi0PtMA5k8HzFp79YGzNt010qPzx4UxSuKr6DHJK4ai1g3Eu5AYgi4uFRKr2JJUIUeYVMDDQffXSfPvxVnaV3NtwNiDU3EMWohmDjefGVc1eyciwqYSe4LVh2MCerfynVFi/DC4LwKD/F+ZfVaioaPtaiIZwGkjpG+N3bLW7qwJ2PCFNtgGubBspMkjWuK9p+yWvhI+IB1O3Gw40iowWOc1SRIoh82wYU9MeOOBh4U0Q8jtgHfWpdKmvL3yYc5h6bH00=
  file:
    - karen.x64.exe
    - karen.x64.o
  on:
    tags: true
