[package]
name = "karen"
version = "0.1.0"
authors = ["Lukas Breuer <lukas.breuer@outlook.com>"]

[dependencies]
    discord = "0.6.0"
    mysql = "7.1.2"
    slog = "1.2.1"
    slog-term = "1.3.2"
    slog-atomic = "0.4.0"
    slog-stream = "1.2.0"
