site_name: Karen (Discord Bot)
theme: cinder

site_url: http://meetkaren.xyz
site_description: A highgly efficient, multipurpose Discord bot written in Rust.
site_author: sn0w

copyright: sn0w - 2016

google_analytics: ["UA-68868516-2", "meetkaren.xyz"]

repo_url: https://github.com/sn0w/karen

markdown_extensions:
  - codehilite
  - unimoji
  - pymdownx.githubemoji
  - pymdownx.magiclink
  - pymdownx.betterem
  - pymdownx.tilde
  - pymdownx.tasklist
  - pymdownx.headeranchor
  - pymdownx.superfences

pages:
  - Home: index.md
  - Legacy (Shiro): legacy.md
  - Testimonials \o/: testimonials.md
  - Family Tree: tree.md

remote_branch: gh-pages
remote_name: gh-pages
